# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 21:21
from __future__ import unicode_literals

from django.db import migrations


def create_data(apps, schema_editor):
    Cat = apps.get_model("cats", "Cat")
    Cat(name="Lil Bub").save()
    Cat(name="Grumpy").save()

class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
